### ISSUE TITLE
Externer Datenschutzlink

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/cookie_consent#10]
Bitte die Möglichkeit einbauen, nicht nur einen internen Link, sondern einen externen zu setzen.
Ich habe einen Kunden mit 3-4 Subdomains und die Subdomains linken alle in den "Master-Datenschutz". Ich hab das jetzt über ein Weiterleitungsmodul realisiert, wäre cool, wenn man das direkt steuern könnte.

**Comment by chrison94** [comment]
Ist drin, werde das demnächst nochmal "aufhübschen" dass man die ausgeblendeten punkte auch nicht mehr sieht.. nur meine javascript parent() Kenntnisse sind wohl nicht ausgeprägt genug dafür gerade
