### ISSUE TITLE
opt-in Methode:  Cookie "dismiss" verschwindet beim ersten Seitenwechsel

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/cookie_consent#106]
(Version 3.0.0-beta3)

Bei opt-in verschwindet das Cookie "dismiss" beim ersten Seitenwechsel und der Cookie-Hinweis wird wieder eingeblendet.

**Comment by webregie** [comment]
Dem schließe ich mich an mit einer ähnlichen Frage: Wie kann man es erreichen, dass das kleine Kästchen, das am unteren Rand ist,  immer zur Verfügung steht? Sobald man die Seite wechselt, ist die Cookie Entscheidung nicht mehr aufrufbar. CSS und JS habe ich eingeblendet gelassen.

**Comment by skerbis** [comment]
@bloep ping.  ... Dissmiss wirkt sich nicht auf die Bannerdarstellung aus. Das Banner wird immer geladen.

**Comment by webregie** [comment]
@fietstouring Hast du denn Analytics über das Feld sinnvoll einbinden können? Würdest du deinen Code teilen?

**Comment by fietstouring** [comment]
ich würde sagen so wie hier #112 nur eben eine Funktion für Google Analytics statt matomoTracking()

**Comment by fietstouring** [comment]
hier noch ein Beispiel... alle Funktionen die Cookies setzen in eine eigene Funktion packen
https://2gdpr.com/cookieconsent
