### ISSUE TITLE
PHP Methode fürs JavaScript

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/cookie_consent#11]
Hi,

das AddOn ist soweit super jedoch hätte ich eine bitte: eine simple Methode, welches den Markup ausspuckt.

```php
echo cookie_consent::getInlineJavascript()
```

Oder sowas in der Art. 1x im REDAXO Template eingefügt, muss man ansonsten ständig den Code tauschen, wenn man z.B. den Text oder den Style ändert.

Und bitte AddOn im Installer bereitstellen, ui-tools gehört da auch hin :)

**Comment by chrison94** [comment]
kann nun mittels `echo cookie_consent::cookie_consent_output();` aufgerufen werden

Kommt dann nachher auch in den Installer :)

ui-tools ist meine ich aber im Installer

**Comment by Hirbod** [comment]
Danke :))

**Comment by Hirbod** [comment]
Sollte noch als Info in die Readme. Aktuell wird zwar darüber gesprochen, aber das konkrete Code-Beispiel fehlt

**Comment by skerbis** [comment]
@Hirbod es steht im Abschnitt Installation. Das Wording wird angepasst.
