### ISSUE TITLE
Opt-In Lösung mit Matomo und Cookieconsent

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cookie_consent#15]
Hier abgucken
https://wwagner.net/typo3/opt-in-loesung-typo3-matomo/

**Comment by bloep** [comment]
Ich habe so etwas auf einfacher Basis schon. Da kann man auch festlegen, dass Cookies so lange vom Server unterbunden werden, bis der Opt-In Cookie gesetzt wurde.
Ich kann morgen mal Screenshots und Co. liefern

**Comment by bloep** [comment]
![image](https://user-images.githubusercontent.com/21292755/40097122-b55a0eb6-58d4-11e8-8980-55d401b19090.png)

So etwas in der Art nehme ich an stellst du dir vor, oder?
