### ISSUE TITLE
Pflicht-Abhängigkeit zum "jquery-minicolors" lösen

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/cookie_consent#16]
Hallo,
ich hätte da ne Frage, ob man die Pflicht-Abhängigkeit zum "jquery-minicolors" nicht lösen könnte?
Sind in der der Datei lib/configuration.php denke ich nur 4 Zeilen Code anzupassen um eine IF-Abfrage,  ob das aktiviert ist oder nicht.

Ansonsten würde halt nur das Texteingabefeld kommen.
Vermutlich würde es auch sofort ein Texteingabefeld werden, wenn die Änhängigkeit in der package.yml nicht eingetragen wäre.

Ansonsten scheint das Addon wirklich super zu klappen.
DANKE an die Entwickler

**Comment by bloep** [comment]
Danke für deinen Vorschlag. Können wir gerne so lösen.

@staabm, @gharlan  Kann man in der `package.yml` optionale Abhängigkeiten hinterlegen? Nach dem Motto würde mit Addon XY eine besser UX bieten..

**Comment by schuer** [comment]
Optionale Abhängigkeiten gibt es nicht, soweit ich weiß. Aber man könnte doch an der Stelle in der View, wo die Minicolors erscheinen würden, einen Hinweis mit Link auf UI-Tools im Installer ergänzen, so dass man die Minicolors ohne viel Aufwand hinzuinstallieren kann.

**Comment by gharlan** [comment]
Bei composer heißt dies "suggest": https://getcomposer.org/doc/04-schema.md#suggest
Sowas gibt es bei uns aber bisher nicht.

**Comment by brandes-webdesign** [comment]
Ich hab das gestern getestet.
In der package.yml diese Zeilen raus und das installieren klappt.

packages:
         ui_tools/jquery-minicolors: '>=2.2.6'

Man hat dann halt die Farbauswahl nicht drinnen, kann aber ja selber den rgba oder hex Wert eintragen.
Wenn man den Farbpicker möchte kann man ja das andere Addon installieren.
Ein kurzer Hinweistext in der Hilfe dazu oder bei der Beschreibung des Addons und die Sache wäre doch dann rund.

Optionale Abhängigkeiten oder so was reinzuprorgammieren ist doch vom Aufwand her nicht vertretbar.

**Comment by bloep** [comment]
@brandes-webdesign Magst du dazu ein PullRequest machen?
