### ISSUE TITLE
Mehrsprachigkeit

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/cookie_consent#18]
Ist kein Issue sonder eher eine Frage, ich weiss nur nicht wo ich das eintragen soll.

Wie schaut es denn mit Mehrsprachigkeit aus bei dem Addon?
Die Hinweis-Texte müssten bei einer Webseite von mir in DE, FR und EN rein.

Gibt es dazu eine Lösung ?

**Comment by tbaddade** [comment]
War letztens Thema im Slack.
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1525351802000353?thread_ts=1525350120.000226&cid=C1BAXLN2F

**Comment by bloep** [comment]
Könnten wir mit aufnehmen

**Comment by bloep** [comment]
Gibt es schon Ideen zu einer möglichen Umsetzung? Sollte man hierbei auf sprog setzen oder etwas eigenes?

**Comment by tbaddade** [comment]
> Sollte man hierbei auf sprog setzen oder etwas eigenes?

Die Abhängigkeit würde ich vermeiden. Wenn man für die Texte im Backend Eingabefelder hat, dann könnte man entweder normalen Text oder eben Platzhalter definieren.
