### ISSUE TITLE
Zusätzliche rechtlichen Anforderungen mitteilen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/cookie_consent#2]
Mit der technischen Einbindung ist es nicht getan. Der Entwickler sollte auf jeden Fall dafür an prominenter Stelle sensibilisiert werden, diese Klassiker zu beachten, die das Skript nutzlos / gefährlich machen:

1. Der Banner verdeckt den Link zum Impressum
2. Datenschutz-Seite nicht vollständig
3. Link zur Datenschutz-Seite nicht korrekt
und ggf. weiterer Ergänzungen....

**Comment by skerbis** [comment]
Gerne als PR

**Comment by skerbis** [comment]
https://www.e-recht24.de/news/abmahnung/10373-cookies-banner-abmahnung.html

**Comment by eaCe** [comment]
Danke für diese Hinweise, auch wenn es nicht in meiner Verantwortung liegt, aber dann machen es 90% aller Webseiten die ich umgesetzt habe falsch :|

**Comment by eaCe** [comment]
In diesem Zusammenhang – kann ich denn verhindern das REDAXO den PHPSESSID cookie automatisch im Frontend setzt? Oder gibt es bei session cookies irgendwelche ausnahmen?

**Comment by skerbis** [comment]
Ich konnte zum. Session Cookie keine Info finden. Im Zweifel einfach in der Datenschutzerklärung erwähnen dass es diese gibt und dass diese nach dem Beenden des Browsers verfällt.

**Comment by skerbis** [comment]
Ich denke, dass es nicht Aufgabe des AddOns ist, rechtliche Rahmenbedingungen zu erläutern. Dies sollte weiterhin in der Verantwortung der Websitebetreiber und Rechtsanwälte verbleiben. Auch Linktipps in der App können ein Problem darstellen.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/cookie_consent/commit/400456c8cec8757874a2f1a10c48427b2d3641d2
