### ISSUE TITLE
Multidomainunterstützung...

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/cookie_consent#23]

**Comment by bloep** [comment]
Am besten manuelles Eintragen ohne Pflicht-Abhängigkeit.
Optionalen Import aus `yrewrite` falls installiert.

@olien Meinung dazu?

**Comment by tbaddade** [comment]
Würde nur prüfen ob yrewrite installiert ist und dann die jeweiligen Domains zur Auswahl geben. 
Da bräuchtest du keine Abhängigkeit definieren.

**Comment by bloep** [comment]
Ohne `yrewrite` keine Multidomainunterstützung wenn ich dich richtig verstanden habe?
Also sobald man `yrewrite` installiert hat, es anbieten ansonsten nicht.

**Comment by tbaddade** [comment]
> Ohne yrewrite keine Multidomainunterstützung wenn ich dich richtig verstanden habe?
> Also sobald man yrewrite installiert hat, es anbieten ansonsten nicht.

Mir ist bisher ansonsten kein anderes AddOn für R5 bekannt.
