### ISSUE TITLE
Assets (JS/CSS) automatisch einbinden

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/cookie_consent#4]
> Die mitgelieferten Javascript cookie_consent_insites.js und CSS cookie_consent_insites.css Dateien im Front-End einbinden

Assets automatisch einbinden? Etwa so wie hier: https://github.com/FriendsOfREDAXO/emailobfuscator/blob/master/boot.php#L27-L37

Dann braucht es allerdings eine zusätzliche Checkbox in den Settings (oder eine andere Methodik), um das automatische Laden zu deaktivieren, falls jemand die Assets manuell einbinden möchte.

**Comment by skerbis** [comment]
Dann muss man ggf. auch noch für den Ausschluss bestimmter Templates sorgen können.

**Comment by chrison94** [comment]
Ich überleg mir nächste Woche da mal was zu :-)

**Comment by chrison94** [comment]
Gibt jetzt eine Checkbox die das automatische einbinden ermöglicht

**Comment by chrison94** [comment]
Funktioniert allerdings nur in Verwendung der bereitgestellten Funktion `echo cookie_consent::cookie_consent_output();`
