### ISSUE TITLE
Benutzerdefinierte Optionen

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/cookie_consent#41]
Cookie Consent lässt mich hier keine Callback-Funktionen wie z.b. onInitialise eingeben.
Dann muss ich den Code erst manuell einbauen...
Unter Konfigurations-Test fehlt ein wichtiges HTML-Tag bei "message".
`<span id='cookieconsent:desc' class='cc-message'>`

**Comment by bloep** [comment]
> Cookie Consent lässt mich hier keine Callback-Funktionen wie z.b. onInitialise eingeben.
Dies ist mir auch schon aufgefallen, bin aber noch nicht dazu gekommen dies zu beheben. Wird aber jetzt zeitnah umgesetzt

> Unter Konfigurations-Test fehlt ein wichtiges HTML-Tag bei "message".
Stimmt, diese Seite muss eh noch auf den aktuellen Stand gebracht werden.

Danke @fietstouring 👍

**Comment by fietstouring** [comment]
Super, danke...
Ich hab diese UI-Tools installiert, aber die Color Picker werden mir nicht angezeigt, muss ich noch was tun außer Addon installieren?

**Comment by bloep** [comment]
das Plugin `ui-tools/jquery-minicolors` muss installiert sein

**Comment by fietstouring** [comment]
thx!
