### ISSUE TITLE
Konfigurations-Test verwaltet

### ISSUE THREAD

**Issue by bloep** [FriendsOfREDAXO/cookie_consent#44]
Die Vorschau-Seite Konfigurations-Test ist nicht auf dem aktuellen Stand. Diese müsste ich die Mehrsprachigkeit und Multidomainunterstützung berücksichtigen.

**Comment by olien** [comment]
Konfigurations-Test  wird bei mir gar nicht aktualisiert bzw. je nach der Konfiguration dargestellt.
