### ISSUE TITLE
Zusatzfeld "impressum"

### ISSUE THREAD

**Issue by medienfeuer** [FriendsOfREDAXO/cookie_consent#50]
Zusätzlich zum Linkfeld "Datenschutz" hätte ich gerne noch eine Möglichkeit, das Impressum im Cookie-Banner zu verlinken (gerne auch optional), um zu vermeiden, dass evtl. kein Impressumslink sichtbar ist, wenn der Cookiebanner es überdeckt.

z.B.: https://i.imgur.com/hWoNKNe.png

**Comment by IngoWinter** [comment]
du kannst die position des banners per addon bestimmen. zusätzlich kannst die position des banners per eigenem css nachjustieren. deswegen finde ich einen link "impressum" im banner über.

**Comment by medienfeuer** [comment]
Position bestimmen macht auf Desktop und Tablets noch Sinn, auf Smartphones (vor allem kleinere) ist schnell mal 50% der Seite verdeckt und man kann sich zwischen Not und Elend (oben oder unten) entscheiden.

**Comment by IngoWinter** [comment]
wenn dein "impressum" link oben steht packst du das banner nach unten und umgekehrt. ich sehe ehrlichgesagt das problem nicht...

**Comment by medienfeuer** [comment]
Wenn der Link zum Impressum im Footer steht, die Hauptnavi oben, dann lege ich den Cookiebanner über die Hauptnavi. Auch blöd. Oder ich baue extra irgendwie dezent oben nen Bereich für das Impressum hin. Das nervt irgendwie.

Deshalb war der Gedanke "Ein kleiner Link im Cookie-Banner zum Impressum kann nicht schaden, dann ist das Impressum und die DSE auf jeden Fall immer erreichbar und ich muss die Seite nicht zugunsten eines Banners umbauen, das eh jeder wegklickt.".

**Comment by bloep** [comment]
Über das Thema habe ich mir noch nie Gedanken gemacht. In erster Linie soll der Cookie-Banner den Benutzer über die Verwendung von Cookies informieren und einen Link zur DSE bieten. Einen Link für das Impressum finde ich persönlich nicht nötig.

Mich würde die Meinung anderer interessieren?

Ich pinge einfach mal ein paar Leute:
@chrison94 @mschnieder @skerbis @alexplusde

**Comment by alexplusde** [comment]
Habe ich auch überlegt. Das Impressum muss immer sichtbar sein. Auf manchen Websites macht es das wirklich einfacher.

**Comment by skerbis** [comment]
Schließe mich @mschnieder  an

**Comment by bloep** [comment]
>  evtl eine zusätzlich Darstellungsmethode per static von oben rein, dann überlagert es nichts.

ist aufgenommen #65 und da das quasi eine alternative bietet, würde ich das hier schließen.
