### ISSUE TITLE
Problem in Verbindung mit yRewrite und REDAXO 5.6

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cookie_consent#54]
![bildschirmfoto 2018-06-06 um 11 22 40](https://user-images.githubusercontent.com/791247/41038009-4b0c4fb6-6995-11e8-8dcb-ae0bbf918978.png)

**Comment by bloep** [comment]
Ah der Fehler kommt generell sobald man keinen Artikel angelegt hat.

**Comment by bloep** [comment]
Ist das nicht eigentlich ein Problem auch in yrewrite. Eigentlich sollte der im optimal Fall abfangen, wenn kein Artikel da ist oder?
//cc @gharlan
