### ISSUE TITLE
Nutzer informieren, das Cookies gespeichert werden | Status = dismiss

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/cookie_consent#63]
Ist der Cookie Status dann richtig? Wäre "allow" nicht richtig?

LG
Oliver

**Comment by bloep** [comment]
`dismiss` wäre hier richtig.

Insites CookieConsent hat drei Zustände:
`deny` - Cookies abgelehnt
`allow` - Cookies zulassen
`dismiss` - "Zur Kenntnis genommen"

**Comment by olien** [comment]
Ah. Danke sehr . War mir nicht klar.
