### ISSUE TITLE
decline button

### ISSUE THREAD

**Issue by mhut47** [FriendsOfREDAXO/cookie_consent#7]
Ist es moglich ein decline button zu realisieren?

**Comment by chrison94** [comment]
Ja, das Script bietet die Möglichkeit an. Was dabei dann passiert, muss man aber selbst verfassen. Werde die Auswahlmöglichkeit beim nächsten Update mit einbauen :-) 

Varianten: https://cookieconsent.insites.com/documentation/compliance/
Callbacks: https://cookieconsent.insites.com/documentation/disabling-cookies/

**Comment by chrison94** [comment]
Ist in der neusten Version mit drin
