### ISSUE TITLE
Cookie consent bei ausgewählten Artikeln nicht anzeigen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cookie_consent#73]
Habe hier gerade den Fall, dass ausgewählte Seiten nur auf einem Fernseher im Hause dargestellt werden sollen. Da bräuchte man den Consent nicht. 

(Mir ist klar, dass ich eine weitere Domain oder Template anlegen könnte, ist aber etwas aufwändig für 2 Artikel)

**Comment by bloep** [comment]
in der aktuellen `beta3` wäre ein Workaround durch den ExtensionPoint `COOKIE_CONSENT_OUTPUT` möglich. Im EP kannst du den Output vom CookieConsent manipulieren und in deinem Fall auf den entsprechenden Seiten einfach das Subject durch einen leeren String ersetzten.

**Comment by skerbis** [comment]
@bloep danke
