### ISSUE TITLE
Standardtexte bitte in Deutsch

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cookie_consent#8]

**Comment by chrison94** [comment]
Meinst du die Beispieltexte wie 'Accept' etc? Fand, da REDAXO ein Multilinguales System ist, Englisch passend

**Comment by skerbis** [comment]
Na ja per default aber erstmal deutsch. Du kannst sie aber auch entsprechend der festgelegten Backendsprache vorbelegen.
