### ISSUE TITLE
yCom vs. cookie_consent

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cookie_consent#84]
Kann es sein, dass Sessions von z. B.  yCom beendet werden? Ich kann bei aktiviertem Cookie Consent keine YCom-geschützte Seite aufrufen.

**Comment by bloep** [comment]
ich nehme an, du hast den Opt-In Modus aktiviert?
Ich hatte selbst schon überlegt, dass man selbst bestimmte Cookies von dem "Lösch"-Verfahren ausschließen kann.

**Comment by skerbis** [comment]
Ja es ist der Opt-In-Modus. Gut in yCom braucht man das Cookie Consent nicht  unbedingt. Vielleicht wäre ein Ausschluss von Kategorien sinnvoll?

**Comment by TobiasKrais** [comment]
Soweit ich das sehe, wird man nicht nur aus einer YCom Session ausgeloggt, sondern auch aus Redaxo.

**Comment by TobiasKrais** [comment]
Danke!

**Comment by skerbis** [comment]
danke
