### ISSUE TITLE
Notice auf der Seite Konfigurationstest

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/cookie_consent#85]
Notice: Undefined variable: REX in /Users/36pixel/daten/webdev/berkel.de/5.0/redaxo/src/addons/cookie_consent/pages/configuration_test.php on line 186
Notice: Undefined variable: REX in /Users/36pixel/daten/webdev/berkel.de/5.0/redaxo/src/addons/cookie_consent/pages/configuration_test.php on line 186

**Comment by bloep** [comment]
Mit [d2619c2](https://github.com/FriendsOfREDAXO/cookie_consent/commit/d2619c231e1573fd6722c713eb2947deda168990) behoben.
