### ISSUE TITLE
Ablehnen-Button bei Modus: "Nutzer informieren, dass Cookies gespeichert werden"?

### ISSUE THREAD

**Issue by Gudruna** [FriendsOfREDAXO/cookie_consent#86]
Wähle ich den Modus: "Nutzer informieren, dass Cookies gespeichert werden " in der Konfiguration aus, erscheinen bei den Text-Einstellungen 2 Felder:
- Text für den Cookie Hinweis 
- Text für den Ablehnen/Verwerfen Button.

Ich brauche einen Accept-Button in diesem Modus, keinen Ablehnen Button, ist ja kein Opt-Out.
Oder soll das der Button sein und das Feld ist in der Konfiguration nur falsch beschriftet?

Und im Modus: Opt-Out steht dann in den Text-Einstellungen : 
- Text für den Cookie Hinweis
- Text für den Ablehnen/Verwerfen Button
- Verweigern-Button-Text (Opt-Out)
Zweimal Ich-will-raus-Button? 
Stimmt das so?

**Comment by bloep** [comment]
Hallo @Gudruna,

ich habe mir das nochmal angeschaut und die Bezeichnung des Buttons ist im Modus "Nutzer informieren,...." nicht passend.

Das Feld ist, wie du sagtest für den Akzeptieren / Bestätigungs-Button.
