### ISSUE TITLE
cookie_consent vs. yrewrite schemes

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cookie_consent#89]
Bei Verwendung eigener Schemes oder des yRewrite schemes AddOns erhalte ich folgende Fehlermeldung und das Scheme wird dann nicht mehr angewendet: 

> Argument 1 passed to rex_structure_element::__construct() must be of the type array, null given, called in /var/www/vhosts/deomain.tld/httpdocs/redaxo/src/addons/structure/lib/structure_element.php on line 163

Cookie Consent Version:  3.0.0-beta2
yRewrite: 2.3

**Comment by TobiasKrais** [comment]
Eventuell ist der Fehler noch weitreichender: https://github.com/yakamara/redaxo_yrewrite/issues/241

**Comment by TobiasKrais** [comment]
@skerbis: kannst du mal testen, ob der Fehler noch kommt, wenn mein Patch der boot.php drin ist?

**Comment by bloep** [comment]
wird vermutlich durch https://github.com/FriendsOfREDAXO/cookie_consent/commit/92ae5cc7651220bd5b2ef2be48884fa01e5225b1 schon behoben sein. Falls nicht, bitte wieder öffnen
