### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/cookie_consent#90]
**page=cookie_consent/configuration_test**

`Notice: Undefined variable: REX in /Users/abc/Sites/abc/redaxo/src/addons/cookie_consent/pages/configuration_test.php on line 186`

REDAXO 5.6.4 (neue Installtion)
PHP 7.2.7

**Comment by TobiasKrais** [comment]
Müsste in der aktuellen Beta behoben sein. Den Issue sollte man schließen können.
